### ISSUE TITLE
Build documentation 

### ISSUE THREAD

**Issue by mstroila** [movetk/movetk#36]
Currently, the CI documentation build process (in the docs folder) causes problems with merging. Need to figure out a different process.

**Comment by bacusters** [comment]
Maybe the cleanest way would be to let the user build his/her own documentation? Next to that, we could maybe host the documentation for the master on a Github Page, [see this link](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/getting-started-with-github-pages). The documentation could then pushed by CI to the repository hosting these page?

**Comment by aniketmitra001** [comment]
Maybe for now we should just set the CMAKE flag **BUILD_DOC=OFF** in the [ci.sh](https://github.com/heremaps/movetk/blob/master/ci.sh) script and also add ```docs/```  ```.gitignore``` 

This will prevent docs to be pushed and the user can build the documentation locally by setting  **BUILD_DOC=ON**
For someone who pulls the docker image of MoveTK it is not an issue as the documentation is generated during [Docker](https://github.com/heremaps/movetk/blob/master/docker/with_jupyterlab/Dockerfile)  build and  will be available to anyone who pulls the docker image and accesses the jupyter notebooks under ```tutorials/``` 

As @bacusters suggested we can have a separate branch that hosts the documentation and a CI pipeline has to be written that pushes code and generates documentation to this branch every time there is a push event on the master branch. 
GitHub Pages can then be configured to point to this branch
<img width="943" alt="Screenshot 2020-10-14 at 15 17 14" src="https://user-images.githubusercontent.com/2693003/95994344-763f2180-0e30-11eb-9540-b5f5f08fd32e.png">

What we need to consider is that now we have two channels  for MoveTK

- https://movetk.win.tue.nl/ 
   - The is a possibility to point GitHub Pages to this domain, however I do not know what is the possibility of hosting documentation on the web-server that serves this site
-  https://heremaps.github.io/movetk/

What we also need to  decide is if we should have  two separate channels?

**Comment by bacusters** [comment]
Sounds indeed good to let the use build the doc when needed locally. I think for the reference/API documentation, it is easiest to put this on GitHub (i.e. GitHub pages @ https://heremaps.github.io/movetk/) . We can then refer to this from the win.tue website. I don't think that is really an issue, since the pages at https://heremaps.github.io/movetk/ would then be the technical documentation, whereas the win.tue website contains contextual info (news, tutorials, maybe high level design philosophy etc.)
